#!C:/Program\ Files/Git/usr/bin/sh.exe

echo "Running git pre-commit hook"

./gradlew tiTree assemble
./gradlew formatKotlin

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0